<?php

namespace Mcc\DataSourceBundle\Repository;

/**
 * CouponCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
