easy_admin:
    entities:
        Command:
            class: Mcc\DataSourceBundle\Entity\Command
            form:
                fields:
                    #- { property: 'tags', type: 'entity', type_options: { multiple: true, class: 'Mcc\DataSourceBundle\Entity\Tag', attr: { data-widget: 'select2' } } }
                    - { property: 'tags', type: 'easyadmin_autocomplete', type_options: { multiple: true, class: 'Mcc\DataSourceBundle\Entity\Tag' } }
                    - { property: 'name'}
            # ...