easy_admin:
    entities:
        Comment:
            #disabled_actions: ['delete', 'edit', 'restock']
            class: Mcc\DataSourceBundle\Entity\Comment
            list:
                fields:
                    ['id', 'content', 'status']
            form:
                fields:
                    - { property: 'content' }
                    - { property: 'status' }
                    #- { property: 'createdAt', type_options: { widget: 'single_text' } }
                    - { property: 'createdAt' }
                    - { property: 'updatedAt' }