easy_admin:
    entities:
        File:
            class: Mcc\DataSourceBundle\Entity\File
#            form:
#                fields:
#                    - { property: 'file', type: 'VichFileType'}
            # ...