easy_admin:
    entities:
        Tag:
            class: Mcc\DataSourceBundle\Entity\Tag
            form:
                fields:
                    - { property: 'posts', type: 'entity', type_options: { class: 'Mcc\DataSourceBundle\Entity\Post' } }
                    - { property: 'name'}
            # ...