services:
#    mcc_backend.example:
#        class: Mcc\BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    acme_hello.twig.extension.debug:
        class:        Mcc\BackendBundle\Twig\BackendTwigExtension
        tags:
             - { name: 'twig.extension' }
